# Generated by Django 3.0.3 on 2020-02-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('release_year', models.SmallIntegerField()),
                ('last_year', models.SmallIntegerField(default='по н.в.')),
            ],
        ),
    ]
