# Generated by Django 3.0.3 on 2020-02-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_year',
            field=models.CharField(default='по н.в.', max_length=50),
        ),
    ]
