# Generated by Django 3.0.3 on 2020-02-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200209_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
