# Generated by Django 3.0.3 on 2020-02-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200209_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='last_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='Until year'),
        ),
        migrations.AlterField(
            model_name='car',
            name='release_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='Since year'),
        ),
    ]
